# (C) 2025 by OPNLAB Development. All rights reserved.
volumes:
  webfire_frontend_dist:

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4200:8000"
    volumes:
      - ./backend:/app
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - no-new-privileges:false
    environment:
      PYTHONUNBUFFERED: 1
      SECRET_KEY: "your-super-secret-key-for-development" # Change this in production!

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run build
    volumes:
      - webfire_frontend_dist:/app/dist

  nginx:
    image: nginx:stable-alpine
    ports:
      - "4280:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - webfire_frontend_dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
